// Copyright 2025 Irreducible Inc.
// Copyright 2026 The Binius Developers

//! Spartan-based proof verification for Binius64 constraint systems.
//!
//! This crate provides the [`Verifier`] struct for verifying zero-knowledge proofs
//! generated by `binius_spartan_prover`. It implements the Spartan protocol adapted
//! for Binius64's constraint system.
//!
//! # When to use this crate
//!
//! Use this crate when you have a constraint system built with `binius_spartan_frontend`
//! and need to verify a Spartan-based proof. This is an alternative to the main
//! `binius_verifier` crate.
//!
//! # Key types
//!
//! - [`Verifier`] - Main verification interface; call [`Verifier::setup`] with a constraint system,
//!   then [`Verifier::verify`] with a proof and public inputs
//! - [`IOPVerifier`] - Core IOP verification logic, independent of the compilation strategy
//! - [`Error`] - Error type returned when proof verification fails
//!
//! # Related crates
//!
//! - `binius_spartan_prover` - Proving counterpart
//! - `binius_spartan_frontend` - Constraint system builder for Spartan
//! - `binius_verifier` - Alternative verification backend

#![warn(rustdoc::missing_crate_level_docs)]

pub mod config;
pub mod constraint_system;
pub mod wiring;

use binius_field::{BinaryField, field::FieldOps};
use binius_iop::{
	basefold_compiler::BaseFoldZKVerifierCompiler,
	channel::{IOPVerifierChannel, OracleLinearRelation, OracleSpec},
};
use binius_ip::channel::IPVerifierChannel;
use binius_math::multilinear::evaluate::evaluate_inplace_scalars;
use binius_spartan_frontend::constraint_system::ConstraintSystem;
use binius_transcript::{VerifierTranscript, fiat_shamir::Challenger};
use binius_utils::{DeserializeBytes, checked_arithmetics::checked_log_2};
use binius_verifier::{
	fri::{self, MinProofSizeStrategy},
	hash::PseudoCompressionFunction,
	merkle_tree::BinaryMerkleTreeScheme,
	protocols::{basefold, mlecheck, sumcheck},
};
use digest::{Digest, Output, core_api::BlockSizeUser};

use crate::constraint_system::{BlindingInfo, ConstraintSystemPadded};

pub const SECURITY_BITS: usize = 96;

/// Output of the multiplication constraint check verification.
#[derive(Debug, Clone)]
pub struct MulcheckOutput<F> {
	/// Evaluation of operand A at the challenge point.
	pub a_eval: F,
	/// Evaluation of operand B at the challenge point.
	pub b_eval: F,
	/// Evaluation of operand C at the challenge point.
	pub c_eval: F,
	/// Evaluation of the mask polynomial at the challenge point.
	pub mask_eval: F,
	/// The challenge point from the sumcheck reduction.
	pub r_x: Vec<F>,
}

/// IOP verifier for a particular constraint system.
///
/// This struct encapsulates the constraint system, providing the core verification logic
/// independent of the specific IOP compilation strategy. Most users should use [`Verifier`]
/// instead, which wraps this with a BaseFold compiler.
#[derive(Debug, Clone)]
pub struct IOPVerifier {
	constraint_system: ConstraintSystemPadded,
}

/// Struct for verifying instances of a particular constraint system.
///
/// The [`Self::setup`] constructor determines public parameters for proving instances of the given
/// constraint system. Then [`Self::verify`] is called one or more times with individual instances.
#[derive(Debug, Clone)]
pub struct Verifier<F, MerkleHash, MerkleCompress>
where
	F: BinaryField,
	MerkleHash: Digest + BlockSizeUser,
	MerkleCompress: PseudoCompressionFunction<Output<MerkleHash>, 2>,
{
	iop_verifier: IOPVerifier,
	/// BaseFold ZK compiler for creating verifier channels.
	basefold_compiler:
		BaseFoldZKVerifierCompiler<F, BinaryMerkleTreeScheme<F, MerkleHash, MerkleCompress>>,
}

impl IOPVerifier {
	/// Constructs an IOP verifier for a constraint system.
	pub fn new(constraint_system: ConstraintSystemPadded) -> Self {
		Self { constraint_system }
	}

	pub fn constraint_system(&self) -> &ConstraintSystemPadded {
		&self.constraint_system
	}

	/// Returns the oracle specs for the IOP channel.
	///
	/// These describe the oracles (witness and mask) that the prover commits to.
	pub fn oracle_specs(&self) -> Vec<OracleSpec> {
		let cs = &self.constraint_system;
		let log_witness_size = cs.log_size() as usize;
		let (m_n, m_d) = cs.mask_dims();
		let log_mask_dim = m_n + m_d;

		vec![
			OracleSpec {
				log_msg_len: log_witness_size,
			},
			OracleSpec {
				log_msg_len: log_mask_dim,
			},
		]
	}

	/// Verifies a proof using an IOP channel.
	///
	/// This is the core verification logic, independent of the specific IOP compilation strategy.
	/// For most users, [`Verifier::verify`] is the simpler interface.
	///
	/// # Arguments
	///
	/// * `public` - The public inputs to the constraint system
	/// * `channel` - The IOP verifier channel
	///
	/// # Returns
	///
	/// `Ok(())` if the proof is valid, `Err(_)` otherwise.
	pub fn verify<F, Channel>(&self, public: &[F], channel: &mut Channel) -> Result<(), Error>
	where
		F: BinaryField,
		Channel: IOPVerifierChannel<F>,
		Channel::Elem: 'static,
	{
		let _verify_guard =
			tracing::info_span!("Verify", operation = "verify", perfetto_category = "operation")
				.entered();

		let cs = &self.constraint_system;

		// Check that the public input length is correct
		if public.len() != 1 << cs.log_public() {
			return Err(Error::IncorrectPublicInputLength {
				expected: 1 << cs.log_public(),
				actual: public.len(),
			});
		}

		// Observe the public input (includes it in Fiat-Shamir).
		let public_elems = channel.observe_many(public);

		// Receive the trace oracle commitment.
		let trace_oracle = channel.recv_oracle()?;

		// Receive the mask oracle commitment.
		let mask_oracle = channel.recv_oracle()?;

		// Verify the multiplication constraints.
		let MulcheckOutput {
			a_eval,
			b_eval,
			c_eval,
			mask_eval,
			r_x,
		} = verify_mulcheck(cs, channel)?;

		// Sample the public input check challenge and evaluate the public input at the challenge
		// point.
		let r_public = channel.sample_many(cs.log_public() as usize);

		let public_eval = evaluate_inplace_scalars(public_elems, &r_public);

		// Compute wiring claim components
		let wiring_claim =
			wiring::compute_claim(cs, &r_public, &[a_eval, b_eval, c_eval], public_eval, channel);

		// Build the transparent closure for the wiring oracle relation
		let trace_transparent = wiring::eval_transparent(
			cs,
			&r_public,
			&r_x,
			wiring_claim.lambda,
			wiring_claim.batch_coeff,
		);

		// Build the transparent closure for the mask oracle relation
		let mask_transparent = mask_transparent(cs, &r_x);

		// Verify both oracle relations (checks are done inside verify_oracle_relations)
		channel.verify_oracle_relations([
			OracleLinearRelation {
				oracle: trace_oracle,
				transparent: trace_transparent,
				claim: wiring_claim.batched_sum,
			},
			OracleLinearRelation {
				oracle: mask_oracle,
				transparent: mask_transparent,
				claim: mask_eval,
			},
		])?;

		Ok(())
	}
}

impl<F, MerkleHash, MerkleCompress> Verifier<F, MerkleHash, MerkleCompress>
where
	F: BinaryField,
	MerkleHash: Digest + BlockSizeUser,
	MerkleCompress: PseudoCompressionFunction<Output<MerkleHash>, 2>,
	Output<MerkleHash>: DeserializeBytes,
{
	/// Constructs a verifier for a constraint system.
	///
	/// See [`Verifier`] struct documentation for details.
	pub fn setup(
		constraint_system: ConstraintSystem,
		log_inv_rate: usize,
		compression: MerkleCompress,
	) -> Result<Self, Error> {
		// Modify the constraint system for zero-knowledge.
		let n_test_queries = fri::calculate_n_test_queries(SECURITY_BITS, log_inv_rate);
		let blinding_info = BlindingInfo {
			n_dummy_wires: n_test_queries,
			// TODO: Document why these are necessary
			n_dummy_constraints: 2,
		};
		let constraint_system = ConstraintSystemPadded::new(constraint_system, blinding_info);

		let iop_verifier = IOPVerifier::new(constraint_system);
		let oracle_specs = iop_verifier.oracle_specs();

		let merkle_scheme = BinaryMerkleTreeScheme::new(compression);

		// Create the BaseFold ZK compiler for IOP verification
		let basefold_compiler = BaseFoldZKVerifierCompiler::new(
			merkle_scheme,
			oracle_specs,
			log_inv_rate,
			n_test_queries,
			&MinProofSizeStrategy,
		);

		Ok(Self {
			iop_verifier,
			basefold_compiler,
		})
	}

	/// Returns a reference to the IOP verifier.
	pub fn iop_verifier(&self) -> &IOPVerifier {
		&self.iop_verifier
	}

	pub fn constraint_system(&self) -> &ConstraintSystemPadded {
		self.iop_verifier.constraint_system()
	}

	/// Returns a reference to the BaseFold ZK verifier compiler.
	pub fn iop_compiler(
		&self,
	) -> &BaseFoldZKVerifierCompiler<F, BinaryMerkleTreeScheme<F, MerkleHash, MerkleCompress>> {
		&self.basefold_compiler
	}

	/// Verifies a proof against the constraint system.
	///
	/// # Arguments
	///
	/// * `public` - The public inputs to the constraint system
	/// * `transcript` - The verifier transcript for Fiat-Shamir
	///
	/// # Preconditions
	///
	/// * The public input length must match the constraint system's public input size
	pub fn verify<Challenger_: Challenger>(
		&self,
		public: &[F],
		transcript: &mut VerifierTranscript<Challenger_>,
	) -> Result<(), Error> {
		// Create channel and delegate to IOPVerifier::verify
		let mut channel = self.basefold_compiler.create_channel(transcript);
		self.iop_verifier.verify(public, &mut channel)
	}
}

fn verify_mulcheck<F, C>(
	cs: &ConstraintSystemPadded,
	channel: &mut C,
) -> Result<MulcheckOutput<C::Elem>, Error>
where
	F: BinaryField,
	C: IPVerifierChannel<F>,
{
	let log_mul_constraints = checked_log_2(cs.mul_constraints().len());

	// Sample random evaluation point
	let r_mulcheck = channel.sample_many(log_mul_constraints);

	// Verify the zerocheck for the multiplication constraints.
	let mlecheck::VerifyZKOutput {
		eval,
		mask_eval,
		challenges: mut r_x,
	} = mlecheck::verify_zk(&r_mulcheck, 2, C::Elem::zero(), channel)?;

	// Reverse because sumcheck binds high-to-low variable indices.
	r_x.reverse();

	// Read the claimed evaluations
	let [a_eval, b_eval, c_eval] = channel.recv_array()?;

	channel.assert_zero(a_eval.clone() * b_eval.clone() - c_eval.clone() - eval)?;

	Ok(MulcheckOutput {
		a_eval,
		b_eval,
		c_eval,
		mask_eval,
		r_x,
	})
}

/// Returns a closure that evaluates the mask transparent polynomial at a given point.
fn mask_transparent<E: FieldOps + 'static>(
	cs: &ConstraintSystemPadded,
	r_x: &[E],
) -> binius_iop::channel::TransparentEvalFn<E> {
	let (_m_n, m_d) = cs.mask_dims();
	let n_vars = r_x.len();
	let mask_degree = 2; // quadratic composition
	let r_x = r_x.to_vec();

	Box::new(move |point: &[E]| {
		// Split into query_k (low-order bits) and query_j (high-order bits).
		let (query_k, query_j) = point.split_at(m_d);

		mlecheck::libra_eval(&r_x, query_j, query_k, n_vars, mask_degree)
	})
}

#[derive(Debug, thiserror::Error)]
pub enum Error {
	#[error("FRI error: {0}")]
	FRI(#[from] fri::Error),
	#[error("Sumcheck error: {0}")]
	Sumcheck(#[from] sumcheck::Error),
	#[error("BaseFold error: {0}")]
	BaseFold(#[from] basefold::Error),
	#[error("wiring error: {0}")]
	Wiring(#[from] wiring::Error),
	#[error("Transcript error: {0}")]
	Transcript(#[from] binius_transcript::Error),
	#[error("IOP channel error: {0}")]
	IOPChannel(#[from] binius_iop::channel::Error),
	#[error("IP channel error: {0}")]
	IPChannel(#[from] binius_ip::channel::Error),
	#[error("incorrect public inputs length: expected {expected}, got {actual}")]
	IncorrectPublicInputLength { expected: usize, actual: usize },
	#[error("incorrect reduction output of the multiplication check")]
	IncorrectMulCheckEvaluation,
}
